Name                    = "Wordpress"
Env                     = "Dev"
Created_by              = "JC"
Dept                    = "IT"
ami                     = "ami-0862aabda3fb488b5"
instance_type           = "t2.micro"
key_name                = "my_WorkingStation"
region                  = "eu-west-1"